language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - npm run build  # build
after_script:
  - 'bash ./script/deploy_gh_page.sh'